

let x:number  = 1  //type inference

console.log(x);


let y:number = 3


function addsum(firstname:number, lastname:number){
    return firstname + lastname    
}
console.log(addsum(2,3))



function adddsum(firstname:number, lastname:number){
    return firstname + lastname
}



function addingsums(one:number, two:number, three:number, four:number):number{
   return  adddsum(one, two) + addsum(three,four)
}





console.log(addingsums(1,2,3,4))

function greet(name:string){
    console.log("HELLO " + name)
}


greet("manu")





// writing the right age 


//  type inferencing. -- getting the type form the previous variable 

function rightage(age:number):boolean{
    if (age > 18){
        return true
    }
    else{
        return false
    }
}

console.log(rightage(20))


// writing a function that will takes another fucntion as the input and then returns after 1second. 



function delaylogic(delayfn:()=> void){
    setTimeout(delayfn,1000);
}


// when ever we want to pass the function as a param then that function doesn't have any arguments then we  have to keep the => void and it means it is empty and doesn't return anythign. 

delaylogic(function (){
    console.log("function delayed");
})


// we can also use the thing called TARGET. where we can use which version of ecma script we want to use. 

// we shouldn't push the .js files that are generated by the ts compiler to the github.



// lets see the interface working principle.

// interface -- classes



interface People{
    names: string;
    age: number;
}


// we cannot implement the class with the type. but we can implement the class with the interface.
type People1 ={
    name: String;
    age: Number;
}

type People2 = {
    name: String;
    gender: String;
}

type mixPerson = People1 & People2 

type optionalMix = People1 | People2

// this is somewhat looks like the extends. -- class  manager extends people 
// but in the type we are having the union of the types. 

// but in the interface we are having the intersection of the interfaces.


class Manager implements People{

    names: string;
    age: number;
    constructor(names:string, age:number){
        this.names= names;
        this.age = age;
    }
}

// here we can add the extra properties also. but we shouldn't miss any property that is there in the interface. 



// ARRAYS IN TYPESCRIPT. 

// for the array type we have to give like nums: number[];

let students : String[];

students = ["manu", "sai"]



